name: geospatial-data-science
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - seaborn
  - jupyter
  - notebook
  - scipy
  - scikit-learn
  - libpysal
  - esda
  - pyproj
  - shapely
  - fiona
  - pyarrow
  - pip:
      - contextily
